---
title: "data_manupilation"
author: "rj2543"
date: "September 19, 2018"
output: github_document
---

```{r}
library(tidyverse)
```

```{r}
options(tibble.print_min = 3)

litters_data = read_csv("./data/FAS_litters.csv",
  col_types = "ccddiiii")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("./data/FAS_pups.csv",
  col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)
```

```{r}
select(litters_data, group, litter_number, gd0_weight, pups_born_alive)
```

```{r}
select(litters_data, group:gd_of_birth)
```

```{r}
select(litters_data, -pups_survive)
```
```{r}
select(litters_data, GROUP = group, LiTtEr_NuMbEr = litter_number)
```

```{r}
rename(litters_data, GROUP = group, LiTtEr_NuMbEr = litter_number)
```

```{r}
select(litters_data, starts_with("gd"))
```

```{r}
select(litters_data, litter_number, everything())
```

```{r}
select(pups_data, litter_number, sex, pd_ears)
```

```{r}
filter(litters_data, gd0_weight < 25)
filter(litters_data, pups_born_alive == 0)
```

```{r}
filter(litters_data, !is.na(gd0_weight))
```

```{r}
filter(litters_data, group == "Low8" | group == "Low7")
```

```{r}
filter(litters_data, group %in% c("Low8", "Low7"))
```

```{r}
mutate(litters_data,
  wt_gain = gd18_weight - gd0_weight,
  group = tolower(group)
)
```

```{r}
mutate(litters_data,
  wt_gain = gd18_weight - gd0_weight,
  wt_gain_squared = wt_gain^2
)
```

```{r}
arrange(litters_data, gd0_weight)
```

```{r}
arrange(litters_data, desc(pups_born_alive), gd0_weight)
```

```{r}
litters_data_raw = read_csv("./data/FAS_litters.csv",
  col_types = "ccddiiii")
litters_data_clean_names = janitor::clean_names(litters_data_raw)
litters_data_selected_cols = select(litters_data_clean_names, -pups_survive)
litters_data_with_vars = mutate(litters_data_selected_cols, 
  wt_gain = gd18_weight - gd0_weight,
  group = tolower(group))
litters_data_with_vars
```

```{r}
litters_data_clean = 
  mutate(
    select(
      janitor::clean_names(
        read_csv("./data/FAS_litters.csv", col_types = "ccddiiii")
        ), 
    -pups_survive
    ),
  wt_gain = gd18_weight - gd0_weight,
  group = tolower(group)
  )
litters_data_clean
```

```{r}
litters_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = tolower(group)
  )
litters_data
```

```{r}
read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = tolower(group)
  ) %>%
  filter(!is.na(gd0_weight)) %>%
  lm(gd18_weight ~ gd0_weight, data = .)
```

```{r}
pulse_data = haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names()
pulse_data
```

```{r}
pulse_tidy_data = gather(pulse_data, key = visit, value = bdi, bdi_score_bl:bdi_score_12m)
pulse_tidy_data
```

```{r}
separate(pulse_tidy_data, visit, into = c("remove_1", "remove_2", "visit"), sep = "_") %>%
  select(-remove_1, -remove_2) %>%
  mutate(visit = replace(visit, visit == "bl", "00m")) 
```

```{r}
pulse_data = haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names() %>%
  gather(key = visit, value = bdi, bdi_score_bl:bdi_score_12m) %>%
  separate(visit, into = c("remove_1", "remove_2", "visit"), sep = "_") %>%
  select(id, visit, everything(), -starts_with("remove")) %>%
  mutate(visit = replace(visit, visit == "bl", "00m"),
         visit = factor(visit, levels = str_c(c("00", "01", "06", "12"), "m"))) %>%
  arrange(id, visit)
print(pulse_data, n = 12)
```

```{r}
read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>% 
  janitor::clean_names() %>%
separate(group, into = c("dose", "day"), 3) %>%
mutate(dose = tolower(dose),
         wt_gain = gd18_weight - gd0_weight) %>%
  arrange(litter_number)

litters_data
```

```{r}
litters_data %>% 
  select(litter_number, ends_with("weight")) %>% 
  gather(key = gd, value = weight, gd0_weight:gd18_weight) %>% 
  mutate(gd = recode(gd, "gd0_weight" = 0, "gd18_weight" = 18))
```

```{r}
analysis_result = tibble(
  group = c("treatment", "treatment", "placebo", "placebo"),
  time = c("pre", "post", "pre", "post"),
  mean = c(4, 8, 3.5, 4)
)
analysis_result
```

```{r}
spread(analysis_result, key = time, value = mean) %>%
knitr::kable()
```

```{r}
fellowship_ring = readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6") %>%
  mutate(movie = "fellowship_ring")

two_towers = readxl::read_excel("./data/LotR_Words.xlsx", range = "F3:H6") %>%
  mutate(movie = "two_towers")

return_king = readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") %>%
  mutate(movie = "return_king")
```


```{r}
lotr_tidy = bind_rows(fellowship_ring, two_towers, return_king) %>%
  janitor::clean_names() %>%
  gather(key = sex, value = words, female:male) %>%
  mutate(race = tolower(race)) %>% 
  select(movie, everything()) 

lotr_tidy
```

```{r}
pup_data = read_csv("./data/FAS_pups.csv", col_types = "ciiiii") %>%
  janitor::clean_names() %>%
  mutate(sex = recode(sex, `1` = "male", `2` = "female")) 

litter_data = read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = tolower(group))

FAS_data = left_join(pup_data, litter_data, by = "litter_number")
FAS_data
```

